export const attributes = [
  {
    School: "Amherst College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Babson College",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Barnard College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Bates College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Boston College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Boston University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Bowdoin College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Brown University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Bryn Mawr College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "California Institute of Technology",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Carleton College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Case Western Reserve University",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Claremont McKenna College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Colby College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Colgate University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Colorado College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Columbia University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Connecticut College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Cornell University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Dartmouth College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Davidson College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Denison University",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Dickinson College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Duke University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Emory University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Franklin & Marshall College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Georgetown University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Grinnell College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Hamilton College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Harvard University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Harvey Mudd College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Haverford College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Johns Hopkins University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Kenyon College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Lafayette College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Lehigh University",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Macalester College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Middlebury College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "MIT",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Mt. Holyoke College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "New York University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Northeastern University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Northwestern University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Oberlin College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Occidental College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Pitzer College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Pomona College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Princeton University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Reed College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Rice University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Scripps College",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Skidmore College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Smith College",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Stanford University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Swarthmore College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Trinity College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Tufts University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "U.S. Air Force Academy",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "U.S. Military Academy",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "U.S. Naval Academy",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Union College",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "University of Chicago",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "University of North Carolina - Chapel Hill",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "University of Notre Dame",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "University of Pennsylvania",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "University of Richmond",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "University of Rochester",
    "Acceptance Rate": "31%+",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "University of Southern California",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "University of Virginia",
    "Acceptance Rate": "21-30%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Vanderbilt University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Vassar College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "No",
  },
  {
    School: "Wake Forest University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "No",
    "Max Out Loans": "Yes",
  },
  {
    School: "Washington & Lee University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Washington University in St. Louis",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Wellesley College",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Wesleyan University",
    "Acceptance Rate": "11-20%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Williams College",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
  {
    School: "Yale University",
    "Acceptance Rate": "0-10%",
    "Top Financial Aid School": "Yes",
    "Max Out Loans": "No",
  },
];
