name: PR Test
on: [pull_request]
jobs:
  commit_stage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test
